variables:
  INSTANCE: 'Writerside/scd'
  DOCKER_VERSION: '243.21565'

stages:
  - build
  - test
  - deploy
  - build_docs
  - test_docs
  - deploy_docs

build:
  stage: build
  image: openjdk:21-jdk-alpine
  only:
    - master
  script:
    - ./gradlew build

test:
  stage: test
  image: openjdk:21-jdk-alpine
  only:
    - master
  script:
    - ./gradlew test

deploy:
  stage: deploy
  image: openjdk:21-jdk-alpine
  only:
    - master
  script:
    - ./gradlew publish
  artifacts:
    paths:
      - build/libs/*.jar
    expire_in: 1 week

build_docs:
  stage: build_docs
  image: registry.jetbrains.team/p/writerside/builder/writerside-builder:$DOCKER_VERSION
  only:
    - master
  script:
    - set -e
    - export DISPLAY=:99
    - Xvfb :99 &
    - PROJECT_ID=$(echo $INSTANCE | cut -d'/' -f2 | tr '[:lower:]' '[:upper:]')
    - ARTIFACT="webHelp${PROJECT_ID}2-all.zip"
    - /opt/builder/bin/idea.sh helpbuilderinspect -source-dir . -product $INSTANCE --runner gitlab -output-dir public
    - echo "Testing existence of $ARTIFACT..."
    - ls -la public
    - test -e public/$ARTIFACT
  artifacts:
    paths:
      - public/$ARTIFACT
      - public/report.json
      - public/$ALGOLIA_ARTIFACT
    expire_in: 1 week

test_docs:
  stage: test_docs
  image: openjdk:18-jdk-alpine
  only:
    - master
  before_script:
    - apk add curl
  script:
    - cd public
    - curl -o wrs-checker.jar -L https://packages.jetbrains.team/maven/p/writerside/maven/com/jetbrains/writerside/writerside-ci-checker/1.0/writerside-ci-checker-1.0.jar
    - java -jar wrs-checker.jar report.json $INSTANCE
  dependencies:
    - build_docs

pages:
  stage: deploy_docs
  image: ubuntu:latest
  only:
    - master
  before_script:
    - apt-get update -y && apt-get install unzip -y

  script:
    - PROJECT_ID=$(echo $INSTANCE | cut -d'/' -f2 | tr '[:lower:]' '[:upper:]')
    - ARTIFACT="webHelp${PROJECT_ID}2-all.zip"
    - echo "Using artifact $ARTIFACT"
    - cd public
    - unzip -O UTF-8 $ARTIFACT
  dependencies:
    - build_docs
  artifacts:
    paths:
      - public
    expire_in: 1 week