package dev.slne.surf.cloud.standalone.player.db.exposed.punishment.entity

import dev.slne.surf.cloud.api.common.player.punishment.type.note.PunishmentNote.PunishmentNoteImpl
import dev.slne.surf.cloud.api.server.exposed.table.AuditableLongEntity
import dev.slne.surf.cloud.api.server.exposed.table.AuditableLongEntityClass
import dev.slne.surf.cloud.standalone.player.db.exposed.punishment.table.*
import org.jetbrains.exposed.dao.LongEntityClass
import org.jetbrains.exposed.dao.id.EntityID

abstract class AbstractPunishmentNoteEntity<E : AbstractPunishmentEntity<E, C>, C : LongEntityClass<E>>(
    id: EntityID<Long>,
    table: AbstractPunishmentNoteTable,
    punishmentEntityClass: C
) : AuditableLongEntity(id, table) {
    var noteId by table.noteId
    var note by table.note
    var creatorId by table.creatorId
    var generated by table.generated

    var punishment by punishmentEntityClass referencedOn table

    fun toApiObject() = PunishmentNoteImpl(
        punishmentId = punishment.punishmentId,
        note = note,
        noteId = noteId,
        isBotNote = generated
    )
}

class BanPunishmentNoteEntity(id: EntityID<Long>) :
    AbstractPunishmentNoteEntity<BanPunishmentEntity, BanPunishmentEntity.Companion>(
        id,
        BanPunishmentNoteTable,
        BanPunishmentEntity
    ) {
    companion object : AuditableLongEntityClass<BanPunishmentNoteEntity>(BanPunishmentNoteTable)
}

class KickPunishmentNoteEntity(id: EntityID<Long>) :
    AbstractPunishmentNoteEntity<KickPunishmentEntity, KickPunishmentEntity.Companion>(
        id,
        KickPunishmentNoteTable,
        KickPunishmentEntity
    ) {
    companion object : AuditableLongEntityClass<KickPunishmentNoteEntity>(KickPunishmentNoteTable)
}

class MutePunishmentNoteEntity(id: EntityID<Long>) :
    AbstractPunishmentNoteEntity<MutePunishmentEntity, MutePunishmentEntity.Companion>(
        id,
        MutePunishmentNoteTable,
        MutePunishmentEntity
    ) {
    companion object : AuditableLongEntityClass<MutePunishmentNoteEntity>(MutePunishmentNoteTable)
}

class WarnPunishmentNoteEntity(id: EntityID<Long>) :
    AbstractPunishmentNoteEntity<WarnPunishmentEntity, WarnPunishmentEntity.Companion>(
        id,
        WarnPunishmentNoteTable,
        WarnPunishmentEntity
    ) {
    companion object : AuditableLongEntityClass<WarnPunishmentNoteEntity>(WarnPunishmentNoteTable)
}